### ISSUE TITLE
Fix problem 5

### ISSUE THREAD

**Issue by johana-star** [noahhs/Ruby-Project-Euler#5]
Problem 5 doesn't work. It returns a "undefined method `p5' for Kernel:Module" error. Refactor so the code works.

**Comment by noahhs** [comment]
Issue is fixed. 

Apparently the issue was caused by problems 3 and 5 using the same global variable. This caused problem 5 to fail if executed after problem 3 in the same runtime session. (Would like to have understood more of what was happening, but ran out of time.)
